In [1]:
%pip install spacy corenlp sentence-transformers

Requirement already satisfied: spacy in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (3.8.11)
Requirement already satisfied: corenlp in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (0.0.14)
Requirement already satisfied: sentence-transformers in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (5.3.0)
Requirement already satisfied: weasel<0.5.0,>=0.4.2 in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from spacy) (0.4.3)
Requirement already satisfied: jinja2 in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from spacy) (3.1.6)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from spacy) (1.0.15)
Requirement already satisfied: setuptools in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from spacy) (65.5.0)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from spacy) (2.32.5)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from spacy) (1.1.3)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from spacy) (3.0.12)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from spacy) (8.3.10)
Requirement already satisfied: typer-slim<1.0.0,>=0.3.0 in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from spacy) (0.24.0)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from spacy) (2.0.10)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from spacy) (4.67.3)
Requirement already satisfied: numpy>=1.19.0 in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from spacy) (1.26.4)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from spacy) (2.5.2)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from spacy) (2.12.5)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from spacy) (3.0.12)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from spacy) (2.0.13)
Requirement already satisfied: packaging>=20.0 in c:\users\armin\appdata\roaming\python\python310\site-packages (from spacy) (26.0)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from spacy) (1.0.5)
Requirement already satisfied: nltk in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from corenlp) (3.9.3)
Requirement already satisfied: scikit-learn in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from sentence-transformers) (1.7.2)
Requirement already satisfied: typing_extensions>=4.5.0 in c:\users\armin\appdata\roaming\python\python310\site-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: huggingface-hub>=0.20.0 in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from sentence-transformers) (1.7.2)
Requirement already satisfied: torch>=1.11.0 in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from sentence-transformers) (2.10.0)
Requirement already satisfied: scipy in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from sentence-transformers) (1.15.3)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from sentence-transformers) (5.3.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2026.2.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.3)
Requirement already satisfied: filelock>=3.10.0 in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.25.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.4.2)
Requirement already satisfied: typer in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.24.1)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.28.1)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.4.2)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.7.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.11)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.2.25)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from thinc<8.4.0,>=8.3.4->spacy) (0.1.5)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from thinc<8.4.0,>=8.3.4->spacy) (1.3.3)
Requirement already satisfied: networkx>=2.5.1 in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.4.2)
Requirement already satisfied: sympy>=1.13.3 in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: colorama in c:\users\armin\appdata\roaming\python\python310\site-packages (from tqdm<5.0.0,>=4.38.0->spacy) (0.4.6)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: regex!=2019.12.17 in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2026.2.28)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from weasel<0.5.0,>=0.4.2->spacy) (7.5.1)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from weasel<0.5.0,>=0.4.2->spacy) (0.23.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from jinja2->spacy) (3.0.3)
Requirement already satisfied: click in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from nltk->corenlp) (8.3.1)
Requirement already satisfied: joblib in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from nltk->corenlp) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: httpcore==1.* in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (1.0.9)
Requirement already satisfied: anyio in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (4.12.1)
Requirement already satisfied: h11>=0.16 in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (0.16.0)
Requirement already satisfied: wrapt in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.4.2->spacy) (2.1.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: rich>=12.3.0 in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (14.3.3)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (0.0.4)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\armin\appdata\roaming\python\python310\site-packages (from rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (2.19.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (4.0.0)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\armin\appdata\roaming\python\python310\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (1.3.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\armin\appdata\local\programs\python\python310\lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

# Text Representation

In [2]:
import pandas as pd 
from spacy.cli import download as spacy_download
from sentence_transformers import SentenceTransformer

# Embedding model
model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

c:\Users\armin\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1974.48it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [3]:
metadata_df = pd.read_parquet('datasets/meta_video_games.parquet') # very large file

# Load train and test data csv files
train_df = pd.read_csv('csv_files/preprocessed_train_video_games.csv')
test_df = pd.read_csv('csv_files/preprocessed_test_video_games.csv')

# Compare the number of common items in train and test data
common_items = set(train_df['item_id']).intersection(set(test_df['item_id']))
print(f'Number of common items in train and test data: {len(common_items)}')

Number of common items in train and test data: 927

To focus the analysis, keep only items that appear in both train and test splits.
This ensures metadata is aligned with the recommendation task.

In [4]:
# Only extract the metadata for the common items in train and test data
common_metadata_df = metadata_df[metadata_df['item_id'].isin(common_items)]
print(f'Number of metadata entries for common items: {len(common_metadata_df)}')

Number of metadata entries for common items: 927

In [5]:
# select the column description from the common metadata dataframe
descriptions = common_metadata_df['description'].tolist()
element = descriptions[0] # its a np.ndarray, we need to convert it to string
type(descriptions[0])

numpy.ndarray

Apply suitable text preprocessing steps, such as tokenization, lowercasing, stopword removal, and stemming/lemmatization.
Justify the selected steps and report vocabulary size before and after preprocessing.

In [6]:
# using the libraries pre process the descriptions
# lower case the descriptions
# can I manipulate in place because downstream I need the asscociated item_id and description, so I will create a new list of clean descriptions
descriptions = common_metadata_df['description'].astype(str).tolist()
# motivate my pre processing steps by understanding the size, and properties of the descriptions
print(f'Number of descriptions: {len(descriptions)}')
print(f'Average length of descriptions: {round(sum(len(desc) for desc in descriptions) / len(descriptions),3)}')
print(f'Maximum length of descriptions: {max(len(desc) for desc in descriptions)}')
print(f'Minimum length of descriptions: {min(len(desc) for desc in descriptions)}')

print(descriptions[0][:300])
# check vocab size 
vocab = set()
for desc in descriptions:
    vocab.update(desc.split())
print(f'Vocabulary size: {len(vocab)}')

Number of descriptions: 927
Average length of descriptions: 2485.95
Maximum length of descriptions: 20881
Minimum length of descriptions: 2
['Amazon.com' 'Long recognized as role-playing games par excellence, the'
 'Final Fantasy'
 'series gets a technological makeover in this installment (and series debut on the PlayStation). Shedding the two-dimensional graphics and limited sound capabilities of its predecessors,'
 'Final Fantasy VII'
Vocabulary size: 40011

### Text Preprocessing

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer
# turn this into a function for any column of text data
# description list is no longer used
def preprocess_text_column(df, column_name):
    
    # convert the column to string type (in case there are any missing values)
    df[column_name] = df[column_name].fillna('').astype(str)
    # lower case
    df[column_name] = df[column_name].str.lower()
    # remove punctuation
    # remove \n and \r characters
    df[column_name] = df[column_name].str.replace('[^\\w\\s]', '', regex=True)
    df[column_name] = df[column_name].str.replace('\n', ' ')
    df[column_name] = df[column_name].str.replace('\r', ' ')
    
    return df

# preprocess the description column
common_metadata_df = preprocess_text_column(common_metadata_df, 'description')

C:\Users\armin\AppData\Local\Temp\ipykernel_5356\4078246216.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column_name] = df[column_name].fillna('').astype(str)
C:\Users\armin\AppData\Local\Temp\ipykernel_5356\4078246216.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column_name] = df[column_name].str.lower()
C:\Users\armin\AppData\Local\Temp\ipykernel_5356\4078246216.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column_name] = df[column_name].str.replace('[^\\w\\s]', '', regex=True)
C:\Users\armin\AppData\Local\Temp\ipykernel_5356\4078246216.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column_name] = df[column_name].str.replace('\n', ' ')
C:\Users\armin\AppData\Local\Temp\ipykernel_5356\4078246216.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column_name] = df[column_name].str.replace('\r', ' ')

In [8]:

# can we check the vocab size after pre processing?
vocab = set()
for desc in common_metadata_df['description']:
    vocab.update(desc.split())
print(f'Vocabulary size after pre processing: {len(vocab)}')
print(common_metadata_df['description'].iloc[0][:300])

Vocabulary size after pre processing: 18765
amazoncom long recognized as roleplaying games par excellence the  final fantasy  series gets a technological makeover in this installment and series debut on the playstation shedding the twodimensional graphics and limited sound capabilities of its predecessors  final fantasy vii  features lush 3d

In [9]:
# count empty descriptions
empty_descriptions = common_metadata_df['description'].str.strip().eq('').sum()
print(f'Number of empty descriptions: {empty_descriptions}')
# remove empty descriptions
common_metadata_df = common_metadata_df[~common_metadata_df['description'].str.strip().eq('')]
print(f'Number of metadata entries after removing empty descriptions: {len(common_metadata_df)}')

Number of empty descriptions: 44
Number of metadata entries after removing empty descriptions: 883

In [23]:
# lets see the data frame after pre processing
common_metadata_df.head()

,item_id,title,description,features,categories,details,rating_number,average_rating
864,B00000JRSB,Final Fantasy VII - PlayStation,amazoncom long recognized as roleplaying games...,"[1 Player, RPG, 3 Disc Set, Excellent graphics...","[Video Games, Legacy Systems, PlayStation Syst...","{'': None, 'AC Adapter Current': None, 'Access...",1631,4.7
1312,B00001X50M,Metal Gear Solid,product description you are snake a governmen...,"[Lightly Armed and facing an army of foes, Sna...","[Video Games, Legacy Systems, PlayStation Syst...","{'': None, 'AC Adapter Current': None, 'Access...",638,4.6
1354,B00001XDUB,Silent Hill,product description in silent hill you assum...,[],"[Video Games, Legacy Systems, PlayStation Syst...","{'': None, 'AC Adapter Current': None, 'Access...",399,4.4
1588,B0000296O5,Final Fantasy VIII,product description game synopsis in a time o...,[],"[Video Games, Legacy Systems, PlayStation Syst...","{'': None, 'AC Adapter Current': None, 'Access...",1394,4.6
5164,B00004Y57G,Final Fantasy IX,final fantasy ixgreatest hits,"[Final Fantasy IX, Dark times have spread over...","[Video Games, Legacy Systems, PlayStation Syst...","{'': None, 'AC Adapter Current': None, 'Access...",1921,4.7

### TF-IDF Representation
The TF-IDF vectorizer handles tokenization internally.

In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer

def tfidf_vectorizing(df, column_name):
    # create a tf-idf vectorizer
    tfidf_vectorizer = TfidfVectorizer(stop_words='english')
    # fit and transform the metadata text data into tf-idf vectors
    tfidf_matrix = tfidf_vectorizer.fit_transform(df[column_name])
    # did we tokenize?
    return tfidf_vectorizer, tfidf_matrix

# apply the tfidf vectorizer to the description column
tfidf_vectorizer, tfidf_matrix = tfidf_vectorizing(common_metadata_df, 'description')
feature_names = tfidf_vectorizer.get_feature_names_out()
item_ids = common_metadata_df['item_id'].tolist()
print(f'TF-IDF matrix shape: {tfidf_matrix.shape}')
print(f'Number of features: {len(feature_names)}')
print(f'Number of unique item ids: {len(set(item_ids))}')

TF-IDF matrix shape: (883, 18440)
Number of features: 18440
Number of unique item ids: 883

### Word Embeddings

In [11]:
# represent each item using pretrained word embeddings, we will use spacy for this task
# create a new column in the processed_metadata_df for the item representation
def compute_item_embeddings(df, column_name):
    # create a new column for the item embeddings
    embeddings = model.encode(df[column_name].tolist())
    df['item_embedding'] = list(embeddings)
    return df
processed_metadata_df = compute_item_embeddings(common_metadata_df, 'description')
processed_metadata_df.head(3)

,item_id,title,description,features,categories,details,rating_number,average_rating,item_embedding
864,B00000JRSB,Final Fantasy VII - PlayStation,amazoncom long recognized as roleplaying games...,"[1 Player, RPG, 3 Disc Set, Excellent graphics...","[Video Games, Legacy Systems, PlayStation Syst...","{'': None, 'AC Adapter Current': None, 'Access...",1631,4.7,"[-0.027039548, -0.00891963, -0.05190869, -0.09..."
1312,B00001X50M,Metal Gear Solid,product description you are snake a governmen...,"[Lightly Armed and facing an army of foes, Sna...","[Video Games, Legacy Systems, PlayStation Syst...","{'': None, 'AC Adapter Current': None, 'Access...",638,4.6,"[-0.08481192, -0.018475069, -0.051596586, -0.0..."
1354,B00001XDUB,Silent Hill,product description in silent hill you assum...,[],"[Video Games, Legacy Systems, PlayStation Syst...","{'': None, 'AC Adapter Current': None, 'Access...",399,4.4,"[-0.020425156, -0.018520003, -0.002381643, 0.0..."

### Similarity: TF-IDF vs Word Embeddings

In [12]:
# compare the similarity between a subset of items by their tf-idf representations
# compare between a subset of the 100 items
from sklearn.metrics.pairwise import cosine_similarity # scale is from -1 to 1
# smaller subset
preview_subset_size = 100
subset_tfidf = tfidf_matrix[:preview_subset_size]
tfidf_sim_preview = cosine_similarity(subset_tfidf)
# comparing embedding representations
subset_embeddings = processed_metadata_df['item_embedding'].tolist()[:preview_subset_size]
embedding_sim_preview = cosine_similarity(subset_embeddings)

subset_titles = common_metadata_df['title'].tolist()[:preview_subset_size]
def show_low_high_pairs(similarity_matrix, titles, method_name, top_k=5):
    
    print(f"\nTop {top_k} most similar pairs based on {method_name}:")
    pairs = []
    for i in range(len(similarity_matrix)):
        for j in range(i + 1, len(similarity_matrix)):
            pairs.append((similarity_matrix[i][j], i, j))
    pairs_sorted = sorted(pairs, key=lambda x: x[0])
    for score, i, j in pairs_sorted[-top_k:][::-1]:
        print(f"{score:.4f} | {titles[i]}  <->  {titles[j]}")
    # low pairs 
    print(f"\n{top_k} least similar pairs based on {method_name}:")
    for score, i, j in pairs_sorted[:top_k]:
        print(f"{score:.4f} | {titles[i]}  <->  {titles[j]}")


show_low_high_pairs(tfidf_sim_preview, subset_titles, "TF-IDF", top_k=5)
show_low_high_pairs(embedding_sim_preview, subset_titles, "Embeddings", top_k=5)

Top 5 most similar pairs based on TF-IDF:
1.0000 | Resident Evil 4 - PlayStation 2  <->  Resident Evil 4
0.5867 | Halo 2 - Xbox  <->  Halo 3 Limited Edition -Xbox 360
0.5195 | Rock Band 2 - Nintendo Wii (Game only)  <->  Rock Band - Nintendo Wii (Game only)
0.4735 | God of War 2 - PlayStation 2  <->  God of War III - Playstation 3
0.4507 | Halo Wars - Xbox 360  <->  Halo 2 - Xbox

5 least similar pairs based on TF-IDF:
0.0000 | Metal Gear Solid  <->  Final Fantasy IX
0.0000 | Metal Gear Solid  <->  Sony PlayStation 3 Blu-ray Disc Remote
0.0000 | Metal Gear Solid  <->  Ninja Gaiden Sigma
0.0000 | Silent Hill  <->  Final Fantasy IX
0.0000 | Silent Hill  <->  Metroid Prime

Top 5 most similar pairs based on Embeddings:
1.0000 | Resident Evil 4 - PlayStation 2  <->  Resident Evil 4
0.7865 | Rock Band - Nintendo Wii (Game only)  <->  Guitar Hero III: Legends of Rock - Xbox 360
0.7437 | PlayStation 3 Dualshock 3 Wireless Controller (Black)  <->  PS3 Wireless Keypad
0.7376 | New Super Mario Bros  <->  Super Mario Galaxy
0.7292 | God of War - PlayStation 2  <->  God of War 2 - PlayStation 2

5 least similar pairs based on Embeddings:
-0.0963 | Legendary - Xbox 360  <->  PS3 Wireless Keypad
-0.0836 | Final Fantasy X-2  <->  PlayStation 3 Dualshock 3 Wireless Controller (Black)
-0.0744 | PlayStation 3 Dualshock 3 Wireless Controller (Black)  <->  Grand Theft Auto IV [Online Game Code]
-0.0708 | Grand Theft Auto IV [Online Game Code]  <->  Tekken 5 - PlayStation 2
-0.0672 | Luigi's Mansion - Gamecube  <->  God of War 2 - PlayStation 2

### Interpretation
TF-IDF tends to capture lexical overlap (shared terms), while embeddings better capture semantic similarity.
As a result, embedding-based pairs can be meaningfully related even when they share fewer exact words.

In this sample, TF-IDF appears more conservative, with lower top similarity scores and stronger dependence on exact term overlap.
Word embeddings produce higher semantic alignment and often identify more intuitively related game descriptions.
Note that all comparisons here are based only on item descriptions.